channels:
  - conda-forge
  - nsls2forge
dependencies:
  - python=3.9
  - amostra
  - area-detector-handlers
  - arvpyf
  - atsas-pipelines
  - blosc
  - bokeh
  - boto3
  - bottleneck
  - chxtools
  - csxtools>=0.1.14
  - dask
  - dask-image
  - dask-jobqueue
  - dask-labextension
  - dask-ml
  - dask-xgboost
  - databroker>=2.0.0b2
  - edrixs
  - eiger-io
  - fabio
  - graphviz
  - h5py
  - hvplot
  - hxntools
  - ipympl
  - jupyterhub-singleuser=1.3.0  # match JupyterHub deployment version
  - jupyterlab=3.2.*
  - line_profiler
  - lixtools
  - lmfit>=0.9.9
  - matplotlib
  - memory_profiler
  - mendeleev
  - modestimage
  - nbclassic>=0.2.8
  - nbgitpuller
  - nbserverproxy
  - netcdf4
  - nodejs
  - nomkl
  - notebook
  - nslsii
  - numba
  - numexpr
  - numpy
  - pandas
  - papermill
  - periodictable
  - photutils
  - pip
  - py-xgboost
  - py4xs
  - pyarrow
  - pycentroids
  - pychx >=4.1.2
  - pyfai
  - pymongo <4
  - pypdf2
  - pystackreg
  - pytables
  - python-blosc
  - python-graphviz
  - pyxrf>=0.0.9
  - reportlab
  - requests
  - sasview
  - scikit-learn
  - scipy
  - seaborn
  # all above OK
  - sip
  - sixtools>=0.0.2
  # tomopy  # causes solve to fail
  - tornado
  - tzlocal <3  # tzlocal 3 broke API on Python 3.7 and the fix turned into a rabbithole
  - voila
  - xarray
  # xpdan
  - xray-vision >=0.0.10
  - xraylarch>=0.9.45
    #   - pip:
    #     # - edrixs
    #     - jupyter-server>=1.15.5
    #     - mimesis
    #     - pyzbar
    #     - smi_analysis
    # 
